---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: conjur-follower
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-follower  # {{ K8S_FOLLOWER_APP_LABEL }}

spec:
  replicas: 1 # {{ K8S_FOLLOWER_REPLICA_COUNT }}
  template:
    metadata:
      labels:
        app: conjur-follower # {{ K8S_FOLLOWER_APP_LABEL }}
        name: conjur-follower # {{ K8S_FOLLOWER_APP_LABEL }}
        role: follower
    spec:
      serviceAccountName: conjur-svc # {{ K8S_FOLLOWER_SVC_ACCT }}
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: authenticator
        image: cyberark/dap-seedfetcher:latest # {{ SEED_FETCHER_REPO }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
          - name: CONJUR_SEED_FILE_URL
            value: {{ CONJUR_SEED_FILE_URL }}
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: FOLLOWER_HOSTNAME
            value: conjur-follower # this should be the same value as the service name
          - name: AUTHENTICATOR_ID
            value: {{ AUTHENTICATOR_ID }}
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}

          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_LOGIN
            value: "{{ CONJUR_AUTHN_LOGIN_PREFIX }}/conjur-cluster"
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur

      containers:
      - name: conjur-appliance
        command: ["/tmp/seedfile/start-follower.sh"]
        image: {{ CONJUR_APPLIANCE_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/{{ AUTHENTICATOR_ID }}
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
