---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: conjur-follower
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-follower
        name: conjur-follower
        role: follower
    spec:
      serviceAccountName: conjur-svc

      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory

      initContainers:
      - name: authenticator
        image: cyberark/dap-seedfetcher:latest
        imagePullPolicy: Always
        env:
          - name: CONJUR_SEED_FILE_URL
            value: https://master1.nate.lab/configuration/lab/seed/follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: FOLLOWER_HOSTNAME
            value: conjur-follower
          - name: AUTHENTICATOR_ID
            value: seed-service
          - name: CONJUR_ACCOUNT
            value: lab

          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/seed-service/conjur/service_account/conjur-svc"
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur

      containers:
      - name: conjur-appliance
        command: ["/tmp/seedfile/start-follower.sh"]
        image: registry.tld/conjur-appliance:11.2.1
        imagePullPolicy: Always
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/lab
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
        ports:
        - containerPort: 443
          name: https
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
